#!/usr/bin/python

import time
import os
import sys
import serial
import urllib2
from datetime import datetime, timedelta
import json
import requests

packet =''

url_local ="http://127.0.0.1:4242/api/put"

def insert(metric_name, tag_site, value):
    data={
        "metric":metric_name,
        "timestamp":time.time(),
        "value":value,
        "tags":{
            "NodeID":tag_site
        }
    }

    ret = requests.post(url_local, data=json.dumps(data))
    time.sleep(1)


def bigEndian(s):
        res = 0
        while len(s):
                s2 = s[0:2]
                s = s[2:]
                res <<=8
                res += eval('0x' + s2)
        return res

def sese(s):

        head = s[:20]
        type = s[36:40]

        serialID = s[24:36]
        nodeID = s[55:56]
        seq = s[40:44]

        batt = s[60:64]


        if type == "0070" : # TH
                #print s
                print "battery : " , bigEndian(batt)
                temperature = bigEndian( s[64:68] )
                v1 = -39.6 + 0.01 * temperature

                t = int(time.time())
                
		insert('temperature',nodeID,v1)

        else:
                #print >> sys.stderr, "Invalid type : " + type
                pass

if __name__ == '__main__':

        tmpPkt = []
        flag = 0

        test = serial.Serial("/dev/ttyUSB0", 115200)

        while 1:
                Data_in = test.read().encode('hex')

                if(Data_in == '7e'):
                        if(flag == 2) :
                                flag =0
                                tmpPkt.append(Data_in)
                                packet = ''.join(tmpPkt)

                                # send packet
                                sese(packet)

                                tmpPkt = []
                                sys.stdout.flush()
                        else :
                                flag = flag + 1
                                tmpPkt.append(Data_in)
                else :
                        if(flag == 1 and Data_in =='45') :
                                flag =2
                        tmpPkt.append(Data_in)
